# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Clock')),
                ('uid', models.CharField(max_length=255, verbose_name='Unique identifier of Clock')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/London')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Team Member')),
                ('clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clocks.Clock')),
            ],
        ),
    ]
