# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 09:05
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='timezone',
        ),
        migrations.AddField(
            model_name='teammember',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
