# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0002_auto_20160430_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='City of Team Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='color',
            field=models.CharField(default='#EEEEEE', max_length=7, verbose_name='Color (HEX)'),
        ),
    ]
